-- USER_INFO CREATE 
/* 
CREATE TABLE [dbo].[USER_INFO](
	[SEQ] [numeric](18, 0) NOT NULL,
	[ID] [nchar](20) NOT NULL,
	[PASSWORD] [nchar](100) NOT NULL,
	[NAME] [nchar](10) NOT NULL,
	[GENDER] [nchar](10) NULL,
	[PHONENO] [nchar](10) NULL,
	[BIRTHDAY] [nchar](10) NULL
) ON [PRIMARY]
*/

--시퀀스 생성
CREATE SEQUENCE [dbo].[USER_SEQ]
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999
CACHE 50 -- 1이면 NOCACHE
;
 
--시퀀스 수정
ALTER SEQUENCE [dbo].[USER_SEQ]
RESTART WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999
CYCLE
CACHE 50 -- 1이면 NOCACHE
 
--시퀀스 삭제
DROP SEQUENCE [dbo].[USER_SEQ]


SELECT * FROM [dbo].[USER_INFO];

INSERT INTO [dbo].[USER_INFO] ([SEQ],[ID],[PASSWORD],[NAME],[GENDER],[PHONENO],[BIRTHDAY])
	VALUES	(NEXT VALUE FOR USER_SEQ,'tester' ,'tester' ,'테스터' ,null ,null ,null);

DELETE FROM [dbo].[USER_INFO]
	WHERE seq = 1;